#!/usr/bin/env python
import cgi,cgitb
cgitb.enable()
form = cgi.FieldStorage()
f_name = form.getvalue('fir_name')
l_name = form.getvalue('lst_name')


print 'content-type:text/html\r\n\r\n'
print '<html>'
print '<center>'
print '<h1> first name is %s </h1>'%(f_name)
print '<h2> last name is %s </h2>'%(l_name)
print '</center>'
print '</html>'



