#!/usr/bin/env python

print 'content-type:text/html\r\n\r\n'
print '<html>'
print '<head>'
print '<title> hello world - first cgi program </title>'
print '</head>'
print '<body>'
print '<h1> hello world: this is my first cgi program </h1>'
print '</body>'
print '</html>'

